### ISSUE TITLE
Image of artist is not shown, due to low resolution should be shown in a small image card

### ISSUE THREAD

**Issue by giovannicolonna** [PRIMETIME4U/PRIMETIME4U-baseclient#18]

**Comment by claudiopastorini** [comment]
IMDb crops and resizes image through URL, for example:

![smallest](http://ia.media-imdb.com/images/M/MV5BMTQ5ODE4NTgzMl5BMl5BanBnXkFtZTcwODI0MjAwMw@@._V1._SX40_CR0,0,40,54_.jpg)
with the URL: http://ia.media-imdb.com/images/M/MV5BMTQ5ODE4NTgzMl5BMl5BanBnXkFtZTcwODI0MjAwMw@@._V1._SX40_CR0,0,40,54_.jpg

![biggest](http://ia.media-imdb.com/images/M/MV5BMTQ5ODE4NTgzMl5BMl5BanBnXkFtZTcwODI0MjAwMw@@)
with the URL: http://ia.media-imdb.com/images/M/MV5BMTQ5ODE4NTgzMl5BMl5BanBnXkFtZTcwODI0MjAwMw@@

We could in app use this system in order to provide the best image resolution for our user with his smartphone.

**Comment by claudiopastorini** [comment]
Try to use [wurfl](http://wurfl.sourceforge.net/) in the future. For now it fixed with medium dimension.
